import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { diff } from "just-diff";

const Home: NextPage = () => {
  const obj1 = { a: 4, b: 5 };
  const obj2 = { a: 3, b: 5 };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          DIFF {`=>`} {JSON.stringify(diff(obj1, obj2))}
        </h1>
      </main>
    </div>
  );
};

export default Home;
